**Numpy**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])                 #create a 1D array
a

array([1, 2, 3])

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])    #create a 2D array

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
lst=[x for x in range(1,20,2)], [x for x in range(1,20,1)]        #createing array using List Comprehension
lst

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

**Array Attributes**

In [ ]:
p = np.array([[x for x in range(2, 21, 2)],[x for x in range(1, 21, 2)]])
p

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [ ]:
p.ndim                 #dimension

2

In [ ]:
p.shape                #will show row and column

(2, 10)

In [ ]:
p.size                 #total element

20

In [ ]:
p.itemsize             #element size

8

In [ ]:
p.dtype                #data type

dtype('int64')

In [ ]:
p.nbytes               #determine how many bytes consumed by the array

In [ ]:
example = np.array([[x for x in range(10, 1, -2)],[x for x in range(9, 0, -2)]])
example

array([[10,  8,  6,  4,  2],
       [ 9,  7,  5,  3,  1]])

In [ ]:
example.shape

(2, 5)

In [ ]:
example.size

10

In [ ]:
example.itemsize

8

In [ ]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


**Slicing and Indexing**

In [ ]:
c = np.array([[9, 5, 8], [5, 8, 3], [2, 9, 0]], dtype = 'int')
print(c)

[[9 5 8]
 [5 8 3]
 [2 9 0]]


In [ ]:
c[0:2, 0:2]

array([[9, 5],
       [5, 8]])

In [ ]:
c[1: ,1:]

array([[8, 3],
       [9, 0]])

In [ ]:
b = np.array([[9, 5, 8], [5, 8, 3]], dtype = 'int')
print(b)

[[9 5 8]
 [5 8 3]]


**Reshape**

In [ ]:
reshaped = np.reshape(b, (3,2))

In [ ]:
reshaped

array([[9, 5],
       [8, 5],
       [8, 3]])

**Transpose**

In [ ]:
np.transpose(reshaped)

array([[9, 8, 8],
       [5, 5, 3]])

In [ ]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

**Shallow Copies**

In [ ]:
b = a.view()
b

array([1, 3, 5, 7, 9])

In [ ]:
b[2]*=6
b

array([ 1,  3, 30,  7,  9])

In [ ]:
a

array([ 1,  3, 30,  7,  9])

**Deep Copies**

In [ ]:
a = np.arange(1, 13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b = a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b[5]*=6
b

array([ 1,  2,  3,  4,  5, 36,  7,  8,  9, 10, 11, 12])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a[1:7]           #slicing

array([2, 3, 4, 5, 6, 7])

**Solution of Slides Problem:**

In [ ]:
Q = np.array([[ 1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16,17,18,19,20]])

In [ ]:
Q

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
Q.shape

(4, 5)

In [ ]:
Q.size

20

In [ ]:
np.reshape(Q, (10,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [ ]:
np.transpose(Q)

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [ ]:
Q[1:2]

array([[ 6,  7,  8,  9, 10]])

In [ ]:
Q[0::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [ ]:
Q[0: , 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [ ]:
Q[2:3, 1:3]

array([[12, 13]])

In [ ]:
Q[2:3,::-1]

array([[15, 14, 13, 12, 11]])

In [ ]:
f = Q[3:]
f

array([[16, 17, 18, 19, 20]])

In [ ]:
print("Maximum:", f.max())
print("Minimum:", f.min())
print("Sum:", f.sum())
print("Mean:", f.mean())
print("Std:", f.std())
print("Variance:", f.var())

Maximum: 20
Minimum: 16
Sum: 90
Mean: 18.0
Std: 1.4142135623730951
Variance: 2.0


In [ ]:
o = Q[0:1]
o

array([[1, 2, 3, 4, 5]])

In [ ]:
print("log10:", np.log10(o))
print("log2:", np.log2(o))
print("log:", np.log(o))

log10: [[0.         0.30103    0.47712125 0.60205999 0.69897   ]]
log2: [[0.         1.         1.5849625  2.         2.32192809]]
log: [[0.         0.69314718 1.09861229 1.38629436 1.60943791]]
